In [1]:
from unicodedata import normalize
import pandas as pd

In [3]:
df = pd.read_csv("dict.csv")

In [7]:
df.sample(10)

,noun,support,len,variation,meaning
10773,chanfaneiros,chanfaneiro,12,4,"[{'class': '', 'meanings': ['Chanfaneiros é o ..."
7109,antropófagas,antropófago,12,4,{'error': 'Request failed with status code 404'}
4147,tumbeiro,tumbeiro,8,4,"[{'class': 'adjetivo', 'meanings': ['Que se re..."
2743,ganesa,ganês,6,4,"[{'class': '', 'meanings': ['Ganesa é o femini..."
10771,chanfaneiras,chanfaneiro,12,4,{'error': 'Request failed with status code 404'}
11232,clamadora,clamador,9,4,"[{'class': '', 'meanings': ['Clamadora é o fem..."
21311,intermediária,intermediário,13,4,"[{'class': 'substantivo feminino', 'meanings':..."
15409,molestadora,molestador,11,4,"[{'class': '', 'meanings': ['Molestadora é o f..."
12950,cavaleiro,cavaleiro,9,4,"[{'class': 'substantivo masculino', 'meanings'..."
10381,checoslovaca,checoslovaco,12,4,"[{'class': '', 'meanings': ['Checoslovaca é o ..."

In [65]:
df.to_csv('data.csv', index = False)